/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FamilyPhotographyRouteImport } from './routes/family-photography'
import { Route as MaternityPhotographyRouteImport } from './routes/maternity-photography'
import { Route as NightlifePhotographyRouteImport } from './routes/nightlife-photography'
import { Route as PortraitPhotographyRouteImport } from './routes/portrait-photography'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyPhotographyRoute = FamilyPhotographyRouteImport.update({
  id: '/family-photography',
  path: '/family-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const MaternityPhotographyRoute = MaternityPhotographyRouteImport.update({
  id: '/maternity-photography',
  path: '/maternity-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const NightlifePhotographyRoute = NightlifePhotographyRouteImport.update({
  id: '/nightlife-photography',
  path: '/nightlife-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitPhotographyRoute = PortraitPhotographyRouteImport.update({
  id: '/portrait-photography',
  path: '/portrait-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/family-photography': typeof FamilyPhotographyRoute
  '/maternity-photography': typeof MaternityPhotographyRoute
  '/nightlife-photography': typeof NightlifePhotographyRoute
  '/portrait-photography': typeof PortraitPhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/family-photography': typeof FamilyPhotographyRoute
  '/maternity-photography': typeof MaternityPhotographyRoute
  '/nightlife-photography': typeof NightlifePhotographyRoute
  '/portrait-photography': typeof PortraitPhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/family-photography': typeof FamilyPhotographyRoute
  '/maternity-photography': typeof MaternityPhotographyRoute
  '/nightlife-photography': typeof NightlifePhotographyRoute
  '/portrait-photography': typeof PortraitPhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/family-photography'
    | '/maternity-photography'
    | '/nightlife-photography'
    | '/portrait-photography'
    | '/privacy'
    | '/services'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/family-photography'
    | '/maternity-photography'
    | '/nightlife-photography'
    | '/portrait-photography'
    | '/privacy'
    | '/services'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/family-photography'
    | '/maternity-photography'
    | '/nightlife-photography'
    | '/portrait-photography'
    | '/privacy'
    | '/services'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FamilyPhotographyRoute: typeof FamilyPhotographyRoute
  MaternityPhotographyRoute: typeof MaternityPhotographyRoute
  NightlifePhotographyRoute: typeof NightlifePhotographyRoute
  PortraitPhotographyRoute: typeof PortraitPhotographyRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-photography': {
      id: '/family-photography'
      path: '/family-photography'
      fullPath: '/family-photography'
      preLoaderRoute: typeof FamilyPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maternity-photography': {
      id: '/maternity-photography'
      path: '/maternity-photography'
      fullPath: '/maternity-photography'
      preLoaderRoute: typeof MaternityPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nightlife-photography': {
      id: '/nightlife-photography'
      path: '/nightlife-photography'
      fullPath: '/nightlife-photography'
      preLoaderRoute: typeof NightlifePhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portrait-photography': {
      id: '/portrait-photography'
      path: '/portrait-photography'
      fullPath: '/portrait-photography'
      preLoaderRoute: typeof PortraitPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FamilyPhotographyRoute: FamilyPhotographyRoute,
  MaternityPhotographyRoute: MaternityPhotographyRoute,
  NightlifePhotographyRoute: NightlifePhotographyRoute,
  PortraitPhotographyRoute: PortraitPhotographyRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
